global:
  scrape_interval: 5s # Test: 5s - Prod: 15-30s

scrape_configs:
  - job_name: 'ingest'
    static_configs:
      - targets: ['172.26.244.116:9091']

  - job_name: 'decode'
    static_configs:
      - targets: ['172.26.244.116:9092']

  - job_name: 'api'
    static_configs:
      - targets: ['172.26.244.116:9093']

  - job_name: 'finalizer'
    static_configs:
      - targets: ['172.26.244.116:9094']