version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: odp-postgres
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER:-admin}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-admin}
      POSTGRES_DB: ${PG_DB:-onchain_data}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    container_name: odp-clickhouse
    restart: always
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_DB: onchain_data
      CLICKHOUSE_USER: ${CH_USER:-default}
      CLICKHOUSE_PASSWORD: ${CH_PASSWORD:-}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - ch_data:/var/lib/clickhouse
      # - ./../db/clickhouse/users.xml:/etc/clickhouse-server/users.xml
    deploy:
      resources:
        limits:
          memory: 6G

  prometheus:
    image: prom/prometheus:latest
    container_name: odp-prometheus
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:latest
    container_name: odp-grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  pg_data:
  ch_data: